^Numpad0::SoundSetVolume 0
^Numpad1::SoundSetVolume 10
^Numpad2::SoundSetVolume 20
^Numpad3::SoundSetVolume 30
^Numpad4::SoundSetVolume 40
^Numpad5::SoundSetVolume 50
^Numpad6::SoundSetVolume 60
^Numpad7::SoundSetVolume 70
^Numpad8::SoundSetVolume 80
^Numpad9::SoundSetVolume 90
^NumpadMult::SoundSetVolume 100
^NumpadAdd::SoundSetVolume "+2"
^NumpadSub::SoundSetVolume "-2"