*~Up::DllCall("mouse_event", "UInt", 0x01, "UInt", 0, "UInt", -1)
*~Down::DllCall("mouse_event", "UInt", 0x01, "UInt", 0, "UInt", 1)
*~Left::DllCall("mouse_event", "UInt", 0x01, "UInt", -1, "UInt", 0)
*~Right::DllCall("mouse_event", "UInt", 0x01, "UInt", 1, "UInt", 0)
;*~Up::MouseMove(0, -1, 0, "R")
;*~Down::MouseMove(0, 1, 0, "R")
;*~Left::MouseMove(-1, 0, 0, "R")
;*~Right::MouseMove(1, 0, 0, "R")